### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/DevPad#7]
### Code
* [x] Proper readable and maintable code with consistent spacing and indentation
* [x] Functions follow the "Do One Thing" rule (single-responsibility)
* [x] Followed DRY (Don’t Repeat Yourself)
* [x] Added comments wherever required
* [x] Proper naming conventions
* [x] Avoided deep nesting

### Readme
* [ ] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [x] Setup (Quick start instructions with how to download and use your project)
* [ ] Contributing (How can others contribute?)
* [ ] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [ ] Wrote tests
* [x] Deployed the project (if possible)
* [ ] Added CI/CD tools to your project (maybe CircleCI or TravisCI) (if possible)

**Comment by anandbaburajan** [comment]
@anasvakyathodi, great work, thanks for contributing and helping others get started with open source! You're just left with a few items in your TODO! For the readme, I'd suggest to refer the readme [here](https://github.com/FOSS-Cell-GECPKD/Hide-it). Also, the `Todo` section in your readme can be made a bit more prominent.

**Comment by anasvakyathodi** [comment]
> @anasvakyathodi, great work, thanks for contributing and helping others get started with open source! You're just left with a few items in your TODO! For the readme, I'd suggest to refer the readme [here](https://github.com/FOSS-Cell-GECPKD/Hide-it). Also, the `Todo` section in your readme can be made a bit more prominent.

Sure @AnandBaburajan ... Thanks for your help :)

**Comment by anandbaburajan** [comment]
Also it would be better if `console.log()` statements were replaced with logging and you can put a `.env.example` too. You can use https://swagger.io/ for the API docs too.

**Comment by anasvakyathodi** [comment]
Okay Thanks @AnandBaburajan
